[build]
  command = "npm ci --include-workspace-root --workspaces && npm run -w @sporx/admin-web build"

[build.environment]
  NODE_VERSION = "20.11.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
